# Generated by Django 2.2.6 on 2019-12-17 17:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Agência de transporte',
                'verbose_name_plural': 'Agências de transporte',
                'db_table': 'denuncias_agencia_transporte',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('ra', models.CharField(blank=True, default='', max_length=200)),
                ('cod_energia', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('cod_inep', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Papeis',
            },
        ),
        migrations.CreateModel(
            name='ReclamacaoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'denuncias_reclamacao_status',
            },
        ),
        migrations.CreateModel(
            name='Reclamante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('sub_novo', models.UUIDField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='SRE',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SREs',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoReclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Setor')),
            ],
            options={
                'verbose_name_plural': 'Tipos de reclamações',
                'db_table': 'denuncias_tipo_reclamacao',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('cod_linha', models.CharField(blank=True, default='', max_length=60)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escola', to='denuncias.Escola')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='denuncias.Turno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.SRE')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('outro_papel', models.CharField(blank=True, default='', max_length=255)),
                ('protocolo', models.CharField(default='', max_length=60)),
                ('data_ocorrido', models.DateTimeField()),
                ('placa_veiculo', models.CharField(blank=True, default='', max_length=255)),
                ('outro_tipo', models.CharField(blank=True, default='', max_length=255)),
                ('agencia_transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='denuncias.AgenciaTransporte')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='denuncias.Aluno')),
                ('papel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='denuncias.Papel')),
                ('reclamante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='denuncias.Reclamante')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Rota')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='denuncias.ReclamacaoStatus')),
                ('tipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='denuncias.TipoReclamacao')),
            ],
            options={
                'verbose_name_plural': 'Reclamações',
            },
        ),
        migrations.CreateModel(
            name='ParecerFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('reclamacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parecer_final', to='denuncias.Reclamacao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Responsavel')),
            ],
            options={
                'db_table': 'denuncias_parecer_final',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('cod_ibge', models.CharField(max_length=200)),
                ('sre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.SRE')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='escola',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Municipio'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('reclamacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='denuncias.Reclamacao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Responsavel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.Escola'),
        ),
        migrations.AddField(
            model_name='agenciatransporte',
            name='sre',
            field=models.ManyToManyField(to='denuncias.SRE'),
        ),
    ]
