# Generated by Django 2.2.6 on 2019-10-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacao',
            name='protocolo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
