# Generated by Django 2.1.13 on 2019-10-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cod_energia',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ra',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='cod_linha',
            field=models.CharField(default='', max_length=60),
        ),
    ]
